---
version: 2
updates:

  # Go mod

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  # # GitHub Actions

  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"

  # # Dockerfiles

  # - package-ecosystem: "docker"
  #   directory: "/deploy"
  #   schedule:
  #     interval: "weekly"
